sources:
     - name : dem_db
       database : demo_db
       schema : demo_sc
       tables:
        - name : T1
        - name:  T2
        - name : T3
    
     - name: src_db
       database: demo_dev_db
       schema:  raw_sc
       tables:
         - name: T7
         - name: Amazon_Customers

     - name: AD_db
       database: AADHAR_DEV_DB
       schema : AADHAR_DEV_SC
       tables:
         - name: Employee_T 
         - name: Employee_A
         - name: Employee_H
         - name: orders_datastg
         - name: employees_Data






